import org.gradle.api.internal.tasks.compile.CompileJavaBuildOperationType

/*
 * This file was generated by the Gradle 'init' task.
 */

description = "library-demo"
group = "ru.athena"
version = "0.0.1-SNAPSHOT"

plugins{
    java
}


subprojects {
    group = "ru.athena"
    version = "0.0.1-SNAPSHOT"
    apply(plugin = "java")
    java.sourceCompatibility = JavaVersion.VERSION_17
    java.toolchain.languageVersion = JavaLanguageVersion.of(17)
    repositories {
        mavenLocal()
        mavenCentral()
        maven {
            url = uri("https://company/com/maven2")
        }
    }
    tasks.withType<JavaCompile> {
        options.compilerArgs.add("-Xlint:deprecation")
    }
}


