CREATE SCHEMA LIBRARY

CREATE TABLE IF NOT EXISTS LIBRARY.BOOKS (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name varchar(50) not null,
    author varchar(50),
    genre varchar(50),
    release_date date,
    reserved varchar(50)
);